### PR TITLE
Add UART howto

### PR DESCRIPTION
**Pull request by 0n41rd4**

### CODE REVIEW

**Comment by rkratky** [comment]
This seems to partially (the part about flashing images to cards) duplicate the work done in #9.

**Comment by 0n41rd4** [comment]
@rkratky I removed the duplicated part

**Comment by xypron** [comment]
@0n41rd4 I have now merged #9 so that you can base your work on it.

**Comment by xypron** [comment]
@0n41rd4 Thanks for looking into the UART description.

* %s/sudo picocom -b 115200 /dev/ttyUSB/sudo picocom -b 115200 /dev/ttyUSB0/

Fyi:
* 'picocom' works great most of the time. Upstream picocom allows to limit the rate at which characters are transferred which can be handy when pasting to U-Boot or GRUB.
* 'tio' is an alternative for 'picocom'. It integrates support for Xmodem and Ymodem whereas picocom relies on external programs (sx, sz). Specifically sx is not compatible with the Xmodem implementation of the StarFive JH7110 SoC. 
* If you are a purist, you could use 'screen'.

**Comment by xypron** [comment]
@0n41rd4 

* Please, mention that you have to be in the 'dialout' group to access serial interfaces.
* Please, remove trailing whitespace.

**Comment by waveform80** [comment]
Good start, and thanks to your other PR fixing the links, the tests now pass (excepting the spellcheck test which is broken due to problems with the sphinx extension). I'm hoping to add some sections on:

* voltage levels (something along the lines of "don't use PC serial adapters or they'll fry your GPIOs", "use TTL adapters because almost all SBCs expect 3.3V serial")
* common wire colouring (already hinted at the in the board-specific UART sections) and options (115200 baud is *almost* universal; 8N1 parity and stop bits is universal -- haven't seen a variation on that in well over a decade)
* handling terminal sizes in a serial console (the serial client cannot implicitly communicate its screen size, and this typically has to be done manually with `stty`)
* handling pastes with serial connections that lack flow control (as the vast majority of SBCs UARTs don't expose RTS/CTS or require additional configuration to do so) -- as Heinrich as noted, picocom upstream can help here (and `screen` has options to introduce inter-key delays for pasting)

Anyway, I'll merge this for now and see if I can find some time to write up those sections!

**Pull request merged**
